{{- if .Values.persistence.gitlabData.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-data
  annotations:
  {{- if .Values.persistence.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.gitlabData.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.gitlabData.size | quote }}
  selector:
    matchLabels:
      volume: {{ template "fullname" . }}-data
{{- end }}
