{{- if .Values.persistence.gitlabEtc.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}-etc
  annotations:
  {{- if .Values.persistence.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.gitlabEtc.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.gitlabEtc.size | quote }}
  selector:
    matchLabels:
      volume: {{ template "fullname" . }}-etc
{{- end }}
